/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AlCard {
    }
}
declare global {
    interface HTMLAlCardElement extends Components.AlCard, HTMLStencilElement {
    }
    var HTMLAlCardElement: {
        prototype: HTMLAlCardElement;
        new (): HTMLAlCardElement;
    };
    interface HTMLElementTagNameMap {
        "al-card": HTMLAlCardElement;
    }
}
declare namespace LocalJSX {
    interface AlCard {
    }
    interface IntrinsicElements {
        "al-card": AlCard;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "al-card": LocalJSX.AlCard & JSXBase.HTMLAttributes<HTMLAlCardElement>;
        }
    }
}
